from enum import Enum


class SQLPort(Enum):
    SQLITE_URL = 'SQLITE_URL'


class NoSQLPort(Enum):
    REMOTE_MONGO_URI = 'REMOTE_MONGO_URI'
    LOCAL_MONGO_URI = 'LOCAL_MONGO_URI'
    MONGO_CLIENT = 'MONGO_CLIENT'
    MONGO_COLLECTION = 'MONGO_COLLECTION'
