class ColorProp:
    WHITE = 'white'
    BLACK = 'black'
    SLATE = 'slate'
    GRAY = 'gray'
    ZINC = 'zinc'
    NEUTRAL = 'neutral'
    STONE = 'stone'
    RED = 'red'
    PINK = 'pink'
    PURPLE = 'purple'
    DEEP_PURPLE = 'deep-purple'
    INDIGO = 'indigo'
    BLUE = 'blue'
    LIGHT_BLUE = 'light-blue'
    CYAN = 'cyan'
    TEAL = 'teal'
    EMERALD = 'emerald'
    GREEN = 'green'
    LIGHT_GREEN = 'light-green'
    LIME = 'lime'
    YELLOW = 'yellow'
    AMBER = 'amber'
    ORANGE = 'orange'
    DEEP_ORANGE = 'deep-orange'
    BROWN = 'brown'


class IntensityProp:
    _50 = '50'
    _100 = '100'
    _200 = '200'
    _300 = '300'
    _400 = '400'
    _500 = '500'
    _600 = '600'
    _700 = '700'
    _800 = '800'
    _900 = '900'

class FormatProp:
    HEX = 'hex'
    RGB = 'rgb'